#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🚀 Checking all tests before pushing'

# Checking all tests
npm test || {
  echo '❌ Something wrong with tests. See more information above ❌'
  exit 2;
}

echo '✅ All tests passed, pushing now...'