#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🚀 Checking and fixing code style for your changed files before committing'

# Checking and fixing ESLint and Prettier only for staging files
npx lint-staged || {
  echo '❌ ESLint or Prettier Check Failed. Make the required changes listed above, add changes and try to commit again ❌'
  exit 1;
}

echo '✅ All checks passed, committing now...'